# '01_numpy.ipynb'

- 데이터분석 : 데이터를 분석하여 의사결정에 도움을 준다.
- 통계 vs 데이터분석 vs 머신러닝
    - 통계:데이터를 **요약, 해석하는 수학**(평균, 분산)
    - 데이터분석: **문제를 정의하고 인사이트 도출** (고객 구매 패턴 분석 + 의사결정)
    - 머신러닝: 데이터를 학습하여 **예측** (스팸함 분류, 추천)
- 데이터분석
    - 의사결정 데이터 기반의 근거
    - 패턴 발견, 예측(머신러닝)

- DA Flow (흐름)
    1. 문제정의
    1. 데이터 수집(결측치, 이상치 처리)
    1. 데이터 정제
    1. 탐색- 시각화 (평균, 분포, 상관관계, 막대그래프, 히스토그램)
    1. 통계분석 및 해석 (수학 -> 가설 검정, 회귀분석, 분포)
    1. 결론 도출
- 시트 vs DB vs Python
    - 시트는 편함
    - DB는 대용량 처리 (억단위)
    - 파이썬 시각화, 분석, 머신러닝

- 라이브러리
    - `Numpy`: 빠름(배열 연산)
    - `pandas`: 표(DataFrame) -> `numpy` 기반으로 만들어 짐
    - `matplotlib`: 시각화 자료 
     

In [1]:
import numpy as np
np.arange(10).reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
class Person:
    def __init__(self,name, age):
        self.name = name
        self.age = age
    def talk(self):
        print('hi')
class Student(Person):
    def __init__(self, name, age, weight):
        super().__init__(name, age)
        self.weight = weight
    def talk(self):
        print(f'hi {self.name}, {self.age}')
p1 = Person('이민규',25)
p1.talk()
p2 = Student('이민규', 25, 76)
p2.talk()

hi
hi 이민규, 25


In [7]:
class Person:
    def __init__(self, name ,age, number, email):
        self.name = name
        self.age = age
        self.number = number
        self.email = email
class Student(Person):
    def __init__(self, name, age, number, email, height):
        super().__init__(name, age, number, email)
        self.height = height
    def talk(self):
        print(f'{self.height} & {self.name}')

In [10]:
p2 = Student('이름','나이','숫자','이메일','키')
p2.talk()

키 & 이름


In [ ]:
# 1차원 -> N차원
# N차원 -> 1차원
arr = np.array([[1,2,3],[4,5,6]])

r = arr.ravel() # 뷰(원본 연결) -> 빨리 펼쳐서 보기
f = arr.flatten() # 복사본      -> 안전하게 새로 만들어서 활용

r[0] = 100
f[0] = -100

print(r, f)


[100   2   3   4   5   6] [-100    2    3    4    5    6]


In [125]:
arr = np.array([10, 20, 30, 40 ,50])
print(arr[0], arr[2], arr[1], arr[-1])
arr[0] = 100
print(arr)

# 변경
arr[0] = 100
print(arr)

10 30 20 50
[100  20  30  40  50]
[100  20  30  40  50]


In [ ]:
arr_2d = np.array(
    [
        [1, 2, 3],
        [4, 5 ,6],
    ]
)

In [128]:
# arr_2d = np.array(range(1,10)).reshape(3, 3)
arr_2d = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
#numpy 에서만 지원
arr_2d[0, 0] #arr_2d[0][0] -> r 0, c 0
arr_2d[1, 1] 

arr_2d[1] # 행 접근

#변경
arr_2d[0,0] = 100
arr_2d


array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [134]:
# 슬라이싱
import numpy as np
arr = np.arange(10)
print(
    arr[2:5],
    arr[:5],
    arr[5:]
)
print(
    arr[1:8:2],
    arr[::2]
)

print(
    arr[::-1],
    arr[7:2:-1]
)

[2 3 4] [0 1 2 3 4] [5 6 7 8 9]
[1 3 5 7] [0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0] [7 6 5 4 3]


In [137]:
l = [1, 2, 3, 4]
l[1:3]

#슬라이싱으로 일괄 변경 (Python  X)
arr[3:6] = 100
print(arr)

[  0   1   2 100 100 100   6   7   8   9]


In [37]:
a = [1, 2, 3]
b = [10, 20 ,30]
result = map(lambda x,y: x+y,a,b)
print(list(result))
 

[11, 22, 33]


In [ ]:
arr_2d = np.arange(1,13).reshape(3, -1)
print(arr_2d)

# row(행) 슬라이싱 -> 0, 1 idx 행
print(arr_2d[:2])

# col(열) 슬라이싱 -> 모든 행의 idx 1,2 열
print(arr_2d[:,1:3])
# row / col 동시 슬라이싱
print(arr_2d[1:3,:2])
# 간격지정 -> 행/열 모두 2간격
print(arr_2d[::2, ::2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 5  6]
 [ 9 10]]


In [147]:
# 다차원 배열 슬라이싱으로 변경
print(arr_2d)

# 부분 배열 일괄 변경
arr_2d[0:2, 0:2] = 0
arr_2d
# 열 교체
print(arr_2d[:,3])

# 브로드캐스팅

[[ 0  0  3  4]
 [ 0  0  7  8]
 [ 9 10 11 12]]
[ 4  8 12]


In [154]:
# boolean 인덱싱
# 조건에 따라 배열 요소 선택 - 필터링
# 마스킹 -> T/F 로 바꿈
arr = np.arange(1, 6) #[1, 2, 3, 4, 5]

arr

# 마스킹 -> T/F로 바꿈
mask = arr >3
print(mask, arr)


arr[0] = 100
mask

# 마스킹 배열로 필터링
print(arr[mask])

# 직접 조건
print(arr[arr >3])

#다중 조건
print(arr[(arr > 2 ) & (arr < 5)]) # and 연산
print(arr[(arr == 1 ) | (arr > 3)]) # or 연산

[False False False  True  True] [1 2 3 4 5]
[4 5]
[100   4   5]
[3 4]
[100   4   5]


In [ ]:
# 2 boolean indexing
arr_2d = np.arange(1, 10).reshape(3,3)

arr_2d > 5

print(arr_2d[arr_2d < 6])
# 조건에 맞는 행만 선택
arr_2d[:,0:3:2]
row_mask = np.array([True, False, True])
print(arr_2d)
print(arr_2d[row_mask]) # row T, F, T -> 0, 2row만 뽑음


[1 2 3 4 5]
[[1 2 3]
 [7 8 9]]


In [46]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr,type(arr))
print('차원', arr.ndim)
print('형태', arr.shape)
print('크기', arr.size)

[1 2 3 4 5] <class 'numpy.ndarray'>
차원 1
형태 (5,)
크기 5


In [165]:
# fancy 인덱싱
arr = np.arange(10, 60 ,10)
print(arr[[1, 2]]) # -> arr[1], arr[2] 를 뽑아라
print(arr[[0,2,3]]) # -> arr[0], arr[2], arr[3] 만 가져와라
print()

[20 30]
[10 30 40]



In [ ]:
arr1d = np.array([1,2,3,4,5])
arr1d


array([1, 2, 3, 4, 5])

In [ ]:
arr = np.arange(10, 60 ,10)
print(arr)
print(arr[[1,2]])
print(arr[[0, 2, 3]]) # -> arr[0], arr[2], arr[3] 만 가져와라

In [167]:
arr_2d = np.arange(1,10).reshape(3,3)
print(arr_2d)

arr_2d[0] # row 0
print(arr_2d[[0,2]]) # row 0, 2

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]


In [173]:
max_num = float('-inf')

In [180]:
numbers = [
  [3, 8, 15],
  [7, 1, 9],
  [4, 12, 10],
  [5, 6, 10]
]
len(numbers[0])

3

In [ ]:
f_arr = np.array([1,2,3], dtype = np.float64)


In [198]:
# arr_2d = np.array(range(1, 10)).reshape(3, 3)
arr_2d = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
arr_2d[0,0]

np.int64(1)

In [201]:
arr_2d[:,2] = [100, 200, 300]
print(arr_2d)

[[  1   2 100]
 [  4   5 200]
 [  7   8 300]]


In [204]:
arr = np.arange(6)
mask = arr > 3 
print(mask, arr)
print(arr[arr>3])

[False False False False  True  True] [0 1 2 3 4 5]
[4 5]


In [182]:
l2d = [
    [1, 2, 3],
    [4, 5, 6]
]
arr2d = np.array(l2d)

In [ ]:
# 행과 열, 동시에 선택
print(
    arr_2d[
        [0,1,2],
        [0,2,1]
    ]
)

# 행렬의 열을 순서 바꾸기
print(
    arr_d[
        :, #모든 행
        [2 0 1] # 열 idx를 이렇게 바꿔라
    ]
)

[1 6 8]


In [47]:
l2d = [
    [1,2,3],
    [4,5,6],
]
arr2d = np.array(l2d)
arr2d.ndim, arr2d.shape, arr2d.size

(2, (2, 3), 6)

In [48]:
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [71]:
import numpy as np
range_arr = np.arange(0,10, 2)
print(range_arr)

# 등간격 실수 배열
lin_space = np.linspace(0,1,5)
print(lin_space)
np.array(range(0, 10 , 2))

#로그스케일
log_space = np.logspace(0,2,5) # 10^0부터 10^2까지의 범위에서 5개의 요소라는 뜻 
print(log_space)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[  1.           3.16227766  10.          31.6227766  100.        ]


In [82]:
random = np.random.rand(3,3)
print(random)
normal = np.random.randn(3,3)
print(normal)
# 정수 난수 (0~9, 3*3)
int_random  = np.random.randit(0,10, (3,3))
print(int_random)

# 시드 설정(랜덤 재현 가능)
np.random.seed(42) # 랜덤 상황 42 고정
np.random.rand(3)

[[0.23834921 0.45165573 0.32817421]
 [0.93539729 0.10807426 0.04660758]
 [0.93922902 0.32451034 0.59623349]]
[[-0.55317004 -0.77774466 -0.62805207]
 [-0.44724989 -0.43163991  1.14694177]
 [-1.13870285 -0.59448548  0.56161785]]


AttributeError: module 'numpy.random' has no attribute 'randit'

In [ ]:
# 배열의 데이터 타입
arr = np.array([1,2,3])
print(arr.dtype)

f_arr = np.array([1,2,3],dtype = np.float64)
print(f_arr.dtype)

#데이터 타입 변경 (int -> float)
converted = arr.astype(np.float32) 
print(converted.dtype)

str_arr = np.array([['1.2','2.3','3.4']])
num_arr = str_arr.astype(float) # np.floatXX 라고 지정 안하고 float 쓰면 -> float64
print(num_arr, num_arr.dtype)

int64
float64
float64
[[1.2 2.3 3.4]] float64


In [ ]:
# 4 *4 단위행렬(identity matrix)
np.eye(4)
print(np.random.rand(2,2))
# 3*4 사이즈의 1
np.ones((3,4),dtype = int)
arr_int = np.random.randit(0,10, size = (2,3,4))


[[0.36187727 0.43807325]
 [0.86111306 0.29646118]]


AttributeError: module 'numpy.random' has no attribute 'randit'

In [ ]:
#1칸의 메모리 사용량
print(arr.itemsize) # int64 -> 8byte
print(converted.itemsize) # float32 -> 4byte
print()
# 총 메모리 사용량
print(arr.nbytes) # 8byte * 3칸
print(converted.nbytes) 

In [77]:
# 배열 재구성
arr = np.arange(12)
reshaped = arr.reshape(3, 4) # 3row * 4col
print(arr)
print(reshaped)

reshaped3d = arr.reshape(2,2,3) # 2페이지, 2*3
print(reshaped3d)

#자동계산
auto1 = arr.reshape(3, -1)
auto2 = arr.reshape(-1, 6)
print(auto1)
print(auto2)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
# reshape -> 원본 그대로, 새롱ㄴ 배열 만드
# resize는 원본을 바꾼다.

arr = np.arange(12)
reshaped = arr.reshape(3, 4) # 새로운 배열 리턴
print(reshaped)
print(arr)

arr.resize(3,4)

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [81]:
#1~15 정수 배열 (arange vs array(range))
print(np.arange(1,16),np.array(range(1,16)))
print(np.arange(0,10, 2))

# 0~3까지 균등 6등분 배열
print(np.linspace(0,3,6))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[0 2 4 6 8]
[0.  0.6 1.2 1.8 2.4 3. ]


In [ ]:
z1d = np.zeros(5)
z2d = np.zeros((2,3))
print(z1d, z2d)
o1d = np.ones(5)
o2d = np.ones((2,3))
print(o1d)
print(o2d)
# n으로 채움 -> 5칸 7로 채움
n1d = np.full(5, 7,dtype =float)
n1d
print(n1d)
#빈칸이지만 먼저 만듬
empty = np.empty(3)
empty1 = empty.dtype = int
empty1
print(empty1)


[0. 0. 0. 0. 0.] [[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[7. 7. 7. 7. 7.]
<class 'int'>


In [5]:

        
class Person:
    x = '클래스 변수'
    y = 100
    def __init__(self,x):
        self.x = x
    def talk(self):
        print(self.x)
        print(self.x, self.y)


In [6]:
p = Person('인스턴스변수')
p.talk()
Person.x


인스턴스변수
인스턴스변수 100


'클래스 변수'

In [20]:
python_list = [1, 2, 3, 4, 5]
python1 = []
for i in range(len(python_list)):
    python1.append(python_list[i]*2)
python1

python1 = [x*2 for x in python_list]
python1

[2, 4, 6, 8, 10]

In [208]:
# 10부터 20까지의 정수 배열 생성
arr = np.arange(10, 21)
print('원본', arr)

# 문제1: 배열의 첫 번째, 세 번째, 마지막 요소 출력
print(arr[[0, 2, -1]])

# 문제2: 인덱스 2부터 5까지 요소 출력
print(arr[2:6])
# 문제3: 처음부터 5번째 요소까지 모든 짝수 인덱스 요소 출력
print(arr[0:9:2])
# 문제4: 배열의 요소를 역순으로 출력
print(arr[::-1])

원본 [10 11 12 13 14 15 16 17 18 19 20]
[10 12 20]
[12 13 14 15]
[10 12 14 16 18]
[20 19 18 17 16 15 14 13 12 11 10]


In [220]:
# 3 * 4 matrix
matrix = np.arange(12).reshape(3, 4)
print('원본', matrix)

# 문제1: (1,2) 위치의 요소 출력
print(matrix[1,2])
# 문제2: 두 번째 행 전체 출력
print(matrix[2])
# 문제3: 마지막 열 전체 출력
print(matrix[:,-1])
# 문제4: 첫 번print(째와 세 번째 행의 두 번째와 네 번째 열 요소만 추출
print(matrix[
    [0,2],:][:,[1,3]])

원본 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[ 8  9 10 11]
[ 3  7 11]
[[ 1  3]
 [ 9 11]]


In [ ]:
lst1 = [x for x in range(20) if x % 5 == 0 and x != 0]
print(lst1)
# 문제1: 5의 배수만 선택하여 출력
arr[arr % 5 ==0]

# 문제2: 3보다 크고 15보다 작은 요소 선택

# 문제3: 7의 배수이거나 홀수인 요소 선택

[5, 10, 15]


array([ 5, 10, 15, 20])

In [241]:
lst1 = [x for x in range(20) if x%5 == 0 and x != 0]
lst1

[5, 10, 15]

In [4]:
import numpy as np
r = np.arange(9).reshape(3,3)
r[0] = 100
print(r)
print(r[::2][::2])


[[100 100 100]
 [  3   4   5]
 [  6   7   8]]
[[100 100 100]]


In [6]:

# 가상의 학생 시험 점수 데이터
math_scores = np.array([85, 90, 75, 95, 70, 80, 65, 75, 90, 85])
science_scores = np.array([90, 85, 80, 95, 70, 75, 65, 80, 85, 90])
english_scores = np.array([80, 85, 90, 80, 75, 90, 70, 75, 85, 95])

subjects = ['수학', '과학', '영어']
scores = np.vstack((math_scores, science_scores, english_scores))
# 기본 통계 (과목별 평균, 중앙값, *표준편차*, 최소, 최대)
# 총점 기준 상위 3명 학생의 정보 표시
# | 학생번호(idx) | 수학 | 과학 | 영어 | 총점 |

In [ ]:
for idx, subject in enumerate(scores):
    mean_score = np.mean(subject)
    median_score = np.median(subject)
    min_score = np.min(subject)
    max_score = np.max(subject)
    print(f'{subjects[idx]} 평균: {mean_score}, 중앙값: {median_score}\n 123')

수학 평균: 81.0, 중앙값: 82.5
 123
과학 평균: 81.5, 중앙값: 82.5
 123
영어 평균: 82.5, 중앙값: 82.5
 123


In [23]:
# 과목 총점 배열
total_scores = np.sum(scores,axis = 0)
# 총점 desc 정렬 후 3명 잘라서 idx만 내놔
sum_sort = np.argsort(total_scores)[::-1][:3]
sum_sort
print('학생번호 ')
for idx in sum_sort:
    print(f'{idx + 1:^7}')

학생번호 
  10   
   4   
   9   


In [ ]:
# 과목별 상관관계
correlation = np.corrcoef(scores)

In [ ]:
#

## 선형대수 연산


In [244]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a **2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]
[ 1  4  9 16]


In [245]:
a = np.array([True, False, True, False])
b = np.array([False, True, True, False])
print(a&b)
print( a|b)


[False False  True False]
[ True  True  True False]


In [246]:
# 배열 생성
arr = np.array([1, 2, 3, 4, 5])

# 스칼라 덧셈
print(arr + 10)     # [11 12 13 14 15]

# 스칼라 뺄셈
print(arr - 1)      # [0 1 2 3 4]

# 스칼라 곱셈
print(arr * 2)      # [2 4 6 8 10]

# 스칼라 나눗셈
print(arr / 2)      # [0.5 1.  1.5 2.  2.5]

# 스칼라 거듭제곱
print(arr ** 2)     # [ 1  4  9 16 25]

# 스칼라 비교
print(arr > 3)      # [False False False  True  True]
print(arr == 2)     # [False  True False False False]

[11 12 13 14 15]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[False False False  True  True]
[False  True False False False]


### 매트릭스(행렬) <-> 스칼라(단일값) 연산

In [247]:
# 2차원 배열
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 스칼라 연산
print(arr_2d + 10)
# [[11 12 13]
#  [14 15 16]]

print(arr_2d * 3)
# [[ 3  6  9]
#  [12 15 18]]

[[11 12 13]
 [14 15 16]]
[[ 3  6  9]
 [12 15 18]]


In [248]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10, 20, 30])
#행렬 + 행벡터
matrix + vector

# 열 벡터 브로드캐스팅
col_vec = np.array(
    [
        [100],
        [200]
    ]
)
print(matrix + col_vec)

[[101 102 103]
 [204 205 206]]


In [ ]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10, 20, 30])

print('Matrix shape',matrix.shape)
print('Vector shape',vector.shape)
# 1. Vector (3, ) 가 앞에 1이 추가됨 -> Matrix (1,3) 으로 변함
# 2. 더해야 하는 matrix (2,3)이랑 줄수가 같을 떄까지 row 복사함.

#shape 확인을 하자
; 점+점 -> 선 ->면
print(matrix + vector)
# 1,3이 추가되고 

Matrix shape (2, 3)
Vector shape (3,)
[[11 22 33]
 [14 25 36]]


In [239]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
arr_2d.transpose(),arr_2d.T

[[1 2 3]
 [4 5 6]]


(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [255]:
# 뷰(원본 데이터와 링크)와 복사본(완전 별도) 차이
arr = np.arange(1,6)
print(arr)

# view란 무엇인가?
# 슬라이싱 -> 뷰 생성
view = arr[1:4]
arr[2:4] = 100
print(arr,view)

view[0] = 20
print(arr)

#복사본,,?
copy = arr.copy()
copy[0] = 100
print(arr,copy)

[1 2 3 4 5]
[  1   2 100 100   5] [  2 100 100]
[  1  20 100 100   5]
[  1  20 100 100   5] [100  20 100 100   5]


In [ ]:
arr1 = np.array([8, 12, 6, 10])
arr2 = np.array([3, 4, 1, 20])
print(arr1 ** 2)
print(arr1 ** (1/2), np.sqrt(arr1))

# 각 자리마다 최대값만 모음
print(np.maximum(arr1, arr2))

#arr1 + arr2 의 모든 자리수를 더한 총합
print(np.sum(arr1 + arr2))


[ 64 144  36 100]
[2.82842712 3.46410162 2.44948974 3.16227766] [2.82842712 3.46410162 2.44948974 3.16227766]
[ 8 12  6 20]


In [262]:
# 테스트 배열
x = np.array([0, np.pi/4, np.pi/2, np.pi])
y = np.array([1, 2, 3, 4])

# 삼각함수
print("sin(x) =", np.sin(x))  # [0., 0.70710678, 1., 0.]
print("cos(x) =", np.cos(x))  # [1., 0.70710678, 0., -1.]
print("tan(x) =", np.tan(x))  # [0., 1., 16331239353195370., 0.]

# 역삼각함수
print("arcsin(sin(x)) =", np.arcsin(np.sin(x)))

# 지수와 로그
print("exp(y) =", np.exp(y))  # [2.71828183, 7.3890561, 20.08553692, 54.59815003]
print("log(y) =", np.log(y))  # [0., 0.69314718, 1.09861229, 1.38629436]
print("log10(y) =", np.log10(y))  # [0., 0.30103, 0.47712125, 0.60205999]
print("log2(y) =", np.log2(y))  # [0., 1., 1.58496250, 2.]

# 제곱근과 거듭제곱
print("sqrt(y) =", np.sqrt(y))  # [1., 1.41421356, 1.73205081, 2.]
print("power(y, 2) =", np.power(y, 2))  # [1, 4, 9, 16]

# 절대값과 부호
z = np.array([-2, -1, 0, 1, 2])
print("abs(z) =", np.abs(z))  # [2 1 0 1 2]
print("sign(z) =", np.sign(z))  # [-1 -1  0  1  1]

# 소수점 처리
w = np.array([1.2, 2.7, 3.5, 4.9])
print("floor(w) =", np.floor(w))  # [1. 2. 3. 4.] (내림)
print("ceil(w) =", np.ceil(w))   # [2. 3. 4. 5.] (올림)
print("round(w) =", np.round(w))  # [1. 3. 4. 5.] (반올림)
print("trunc(w) =", np.trunc(w))  # [1. 2. 3. 4.] (소수점 버림)

sin(x) = [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
cos(x) = [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]
tan(x) = [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.22464680e-16]
arcsin(sin(x)) = [0.00000000e+00 7.85398163e-01 1.57079633e+00 1.22464680e-16]
exp(y) = [ 2.71828183  7.3890561  20.08553692 54.59815003]
log(y) = [0.         0.69314718 1.09861229 1.38629436]
log10(y) = [0.         0.30103    0.47712125 0.60205999]
log2(y) = [0.        1.        1.5849625 2.       ]
sqrt(y) = [1.         1.41421356 1.73205081 2.        ]
power(y, 2) = [ 1  4  9 16]
abs(z) = [2 1 0 1 2]
sign(z) = [-1 -1  0  1  1]
floor(w) = [1. 2. 3. 4.]
ceil(w) = [2. 3. 4. 5.]
round(w) = [1. 3. 4. 5.]
trunc(w) = [1. 2. 3. 4.]


In [263]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 기본 집계
print("합계:", np.sum(arr))          # 45
print("평균:", np.mean(arr))         # 5.0
print("최소값:", np.min(arr))        # 1
print("최대값:", np.max(arr))        # 9
print("표준편차:", np.std(arr))      # 2.581988897471611
print("분산:", np.var(arr))          # 6.666666666666667

합계: 45
평균: 5.0
최소값: 1
최대값: 9
표준편차: 2.581988897471611
분산: 6.666666666666667


In [265]:
#샘플 배열
arr = np.arange(12)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

# 균등 분할
print("3개로 균등 분할:")
print(np.split(arr, 3))  # [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

# 위치 지정 분할
print("위치 지정 분할 (인덱스 3, 8 기준):")
print(np.split(arr, [3, 8]))  # [array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([ 8,  9, 10, 11])]

# 2차원 배열 분할
arr_2d = np.arange(16).reshape(4, 4)
print("2차원 배열:")
print(arr_2d)

# 행 방향 분할
print("행 방향 분할:")
print(np.split(arr_2d, 2, axis=0))  # 2개 배열로 (각 2x4)
print(np.vsplit(arr_2d, 2))  # 동일한 결과

# 열 방향 분할
print("열 방향 분할:")
print(np.split(arr_2d, 2, axis=1))  # 2개 배열로 (각 4x2)
print(np.hsplit(arr_2d, 2))  # 동일한 결과

3개로 균등 분할:
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
위치 지정 분할 (인덱스 3, 8 기준):
[array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([ 8,  9, 10, 11])]
2차원 배열:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
행 방향 분할:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
열 방향 분할:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [264]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("누적 곱", np.cumprod(arr))

누적 곱 [     1      2      6     24    120    720   5040  40320 362880]


In [273]:
# 벡터를 차원확장(행이냐 열이냐)
arr = np.array([1,2,3,4])
print(arr)

row_vector = np.expand_dims(arr, axis = 0)
print(row_vector)
row_vector2= arr[np.newaxis,:]
print(row_vector2)
print(row_vector.shape)
#col vector -> [[1] [2] [3] [4]]
col_vector = np.expand_dims(arr, axis = 1)
print(col_vector)
col_vector2 = arr[:, np.newaxis]
print(col_vector2)


[1 2 3 4]
[[1 2 3 4]]
[[1 2 3 4]]
(1, 4)
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]


In [ ]:
# 차원 축소

arr = np.array([ [[1],[2],[3]]])
#모든 단일 차원(shape에서 1 나온 것들) 제거
print(np.squeeze(arr))
# 특정 축만 제거
arr2 = np.array([[[1,2,3]]])
print(arr2, arr2.shape)

print(np.squeeze(arr2,axis= 1))
#상하좌우로 해서 axis = 0, axis =1 로 외운다.
[1,2,3,4]


[1 2 3]
[[[1 2 3]]] (1, 1, 3)
[[1 2 3]]


In [282]:
print(np.squeeze(arr))

[1 2 3]
